##
##      To build the AI_CNET docker image
##

# base stuff
FROM yeepeekoo/public:ai_cnet_

###### update latest OSAIS config (not an absolute requirement) ######

# push again the base files
COPY ./_static/* ./_static
COPY ./_templates/* ./_templates
COPY ./_osais/* .

# copy warmup files
COPY ./_input/warmup.jpg ./_input/warmup.jpg


###### specific AI config (must do) ######
COPY ./ai/models/v1-5-pruned.ckpt ./ai/models/v1-5-pruned.ckpt
COPY ./ai/models/control_v11p_sd15_canny.yaml ./ai/models/control_v11p_sd15_canny.yaml
COPY ./ai/models/control_v11p_sd15_canny.pth ./ai/models/control_v11p_sd15_canny.pth
COPY ./ai/models/clip-vit-large-patch14 ./ai/models/clip-vit-large-patch14
COPY ./ai/annotator ./ai/annotator
COPY ./ai/cldm ./ai/cldm
COPY ./ai/ldm ./ai/ldm
COPY ./ai/share.py ./ai/share.py
COPY ./ai/config.py ./ai/config.py
COPY ./ai/runai.py ./ai/runai.py
COPY ./ai/model ./ai/model
COPY ./ai/config ./ai/config

# keep the transparent image (case of using cnet with prompt only)
COPY ./_input/keep_transparent.png ./_input/keep_transparent.png

# overload config with those default settings
ENV ENGINE=cnet

# run as a server
CMD ["uvicorn", "main_fastapi:app", "--host", "0.0.0.0", "--port", "5108"]
